FROM python:3.11
COPY . .
RUN pip install -r requirements.txt && pip install awslambdaric
RUN apt update && apt install -y ffmpeg
ENTRYPOINT [ "/usr/local/bin/python", "-m", "awslambdaric" ]
CMD [ "app.handler" ]
